### ISSUE TITLE
grid_depth.py->Habitat->get_config()->TypeError: get_config() missing 1 required positional argument: 'config_path'

### ISSUE THREAD

**Issue by Mercy2Green** [MarSaKi/VLN-BEVBert#14]
Hi MarSaKi, I find a problem when I run the /precompute_features/grid_depth.py. Do you have any idea how to solve this problem?

```
TypeError: get_config() missing 1 required positional argument: 'config_path'
```

I run the VLN-BEVBert in a docker and I set up the env using conda. I can successfully run the grid_mp3d_clip.py and the grid_mp3d_imagenet.py.

Thank you.

Env:
Python 3.8
Habitat 0.2.3

![image](https://github.com/MarSaKi/VLN-BEVBert/assets/32302140/9065cbe1-98f4-43f2-b41b-da9b6b45aca7)

**Comment by MarSaKi** [comment]
Hi, you should use Habitat 0.1.7， this repo is not compatible with other versions.

**Comment by Mercy2Green** [comment]
Thank you, I will try it again.

**Comment by Mercy2Green** [comment]
Ok, now I use the Habitat 0.1.7 and python3.6. But I encounter another problem.

```
DISPLAY not detected. For headless systems, compile with --headless for EGL support
```
Do you know how to solve this problem?

![image](https://github.com/MarSaKi/VLN-BEVBert/assets/32302140/fd136d87-7fb6-4b33-a668-a1120f378228)

**Comment by MarSaKi** [comment]
You should install habitat v0.1.7 with headless option, following step 4.
You can ensure the corret installation of your habitat with this [repo](https://github.com/facebookresearch/habitat-lab/tree/v0.1.7)

**Comment by Mercy2Green** [comment]
Sorry, I didn't say it clearly. 

I have installed Habitat v0.1.7 with a headless option and it provided the message above.

I also built it in source code with a headless option but it also showed the same message.

This Habitat v0.1.7 is installed in a docker which can run the Mattersim correctly, and the conda env of Python is 3.6. A part of the code of my docker file is shown below:

```
# BEVBert additional dependencies
RUN source activate bevbert && \
    pip3 install h5py msgpack_numpy tqdm ftfy regex timm && \
    pip3 install progressbar2==3.55.0

# install habitat and habitat_baselines

RUN apt-get install -y git

RUN source activate bevbert && \
    conda install -y habitat-sim=0.1.7 headless -c conda-forge -c aihabitat

RUN source activate bevbert && \
    pip3 install protobuf==3.19.6 && \
    git clone --branch v0.1.7 https://github.com/facebookresearch/habitat-lab.git && \
    cd habitat-lab && \
    python3 setup.py develop --all # install habitat and habitat_baselines

RUN source activate bevbert && \
    pip3 install gym==0.10.9 && \
    gym-notices==0.0.8
```

Thank you.

**Comment by MarSaKi** [comment]
Hi, I guess that you might need to install some EGL dependency.
Please refer to this [issue](https://github.com/facebookresearch/habitat-sim/issues/1511).
![image](https://github.com/MarSaKi/VLN-BEVBert/assets/24617881/7b1d26cf-cab7-4934-a202-4b6cc9090316)

**Comment by Mercy2Green** [comment]
Thank you, I will try it.

**Comment by Mercy2Green** [comment]
I solved this problem by modifying my docker file to the Habitat official docker file in the "https://github.com/facebookresearch/habitat-lab/blob/v0.1.7/Dockerfile".

The Habitat part of the code is shown below.
```
# install habitat and habitat_baselines
RUN source activate bevbert && \
    git clone --branch v0.1.7 https://github.com/facebookresearch/habitat-sim.git && \
    cd habitat-sim && \
    pip3 install -r requirements.txt && \
    python setup.py install --headless

RUN source activate bevbert && \
    pip3 install protobuf==3.19.6 && \
    git clone --branch v0.1.7 https://github.com/facebookresearch/habitat-lab.git && \
    cd habitat-lab && \
    pip3 install -e . && cd .. 

ENV GLOG_minloglevel=2
ENV MAGNUM_LOG="quiet"

RUN source activate bevbert && \
    pip3 install gym==0.17.3
```
@MarSaKi Thank you for guiding me to solve this issue!
