### ISSUE TITLE
img_features/mp3d_224x224_vfov90_bgr.hdf5 files

### ISSUE THREAD

**Issue by statjuns** [MarSaKi/VLN-BEVBert#2]
Thank you for sharing your nice work!!

I'm trying to run the training code but I cannot find img_features/mp3d_224x224_vfov90_bgr.hdf5 and img_features/habitat_224x224_vfov90_depth.hdf5. How can I get the files?

**Comment by MarSaKi** [comment]
Thanks for your interest.
These two files are for visualization not for training. You can comment corresponding vis code if you met errors during training. 
If you want to visualize bev maps, you can refer to the “grid_mp3d_clip.py” and “grid_depth.py” files to directly store RGB and depth images.

**Comment by MarSaKi** [comment]
> Thank you for sharing your nice work!!
> 
> I'm trying to run the training code but I cannot find img_features/mp3d_224x224_vfov90_bgr.hdf5 and img_features/habitat_224x224_vfov90_depth.hdf5. How can I get the files?

I have uploaded image storing scripts in "precompute_features" folder, check it for your convenience.

**Comment by statjuns** [comment]
Wow thanks a lot !
