### ISSUE TITLE
Is augmented data used for R2R task fine-tuning?

### ISSUE THREAD

**Issue by DITINGmisa** [MarSaKi/VLN-BEVBert#26]
Hello MarSaKi, thank you for your excellent work!
I notice the arguments "--aug datasets/R2R/annotations/prevalent_aug_train_enc.json" at VLN-BEVBert/scripts/ft_r2r.bash. When you produce the result in your paper, is augmented data used for R2R task fine-tuning?

**Comment by MarSaKi** [comment]
yes "prevalent_aug_train_enc.json" has been used for fine-tuning
