### ISSUE TITLE
About camera to world transformation

### ISSUE THREAD

**Issue by siqiZ805** [MarSaKi/VLN-BEVBert#27]
Hello MarSaKi, thank you for open soucing your great work! I'm new to bev perception. In my view, the transformation should be look like: 
![image](https://github.com/user-attachments/assets/818f126a-7422-45e9-be50-19445272031a)

I notice that you take the negative value of y in https://github.com/MarSaKi/VLN-BEVBert/blob/161ffdbee6743c8c13365b4b8549aae8aabcb013/pretrain_src/data/dataset.py#L408. Could you please share the reason for doing so?

**Comment by MarSaKi** [comment]
Hi, thanks for your interest.
Frankly speaking, I don't know why to do so, because the coordinate systems of MP3D sim is strange.
I try different options and visualize, if the visualization looks good, I keep it.

**Comment by siqiZ805** [comment]
Thank you for your quick response! The MP3D sim coordinate is indeed confusing/(ㄒoㄒ)/
