### ISSUE TITLE
Bird-eye plot visualization

### ISSUE THREAD

**Issue by mengfeidu** [MarSaKi/VLN-BEVBert#3]
Thank you for sharing your nice work!
How did you visualize the bird-eye plot in Figure 5 reported in your paper？

**Comment by WPixar** [comment]
The same question

**Comment by MarSaKi** [comment]
Thanks for your attention! You can refer to this [script](https://github.com/weituo12321/PREVALENT/blob/master/preprocess/3D/show_trajectories.ipynb) for BEV visualization.

**Comment by mengfeidu** [comment]
Thanks so much!

**Comment by mengfeidu** [comment]
I am trying to visulize following the script, but I get an image that differs from expectations. Have you experienced a similar issue? Thank you!

![image](https://github.com/MarSaKi/VLN-BEVBert/assets/49779908/042396c4-fdc4-46f2-8b03-59a87cd20a82)
