### ISSUE TITLE
R2R-CE pre-training

### ISSUE THREAD

**Issue by yhl2018** [MarSaKi/VLN-BEVBert#4]
执行一下代码一直卡在以下界面呢？
# for R2R-CE pre-training
python precompute_features/grid_habitat_clip.py
![1698676417297](https://github.com/MarSaKi/VLN-BEVBert/assets/36877347/6b4dc681-0d1b-4c6c-915a-751f5d61fd44)

python precompute_features/save_habitat_img.py --img_type depth

![1698676433321](https://github.com/MarSaKi/VLN-BEVBert/assets/36877347/f3652d85-125e-4af6-a288-8e547f9887c9)

**Comment by MarSaKi** [comment]
I guess you should re-compile the Matterport3D simulator in the cpu-mode, because there is conflict between habitat_sim and mp3d_sim_gpu. You can run this command to compile mp3d_sim in CPU mode:
'
mkdir build_cpu && cd build_cpu 
cmake -DOSMESA_RENDERING=ON ..
make
cd ../
'

**Comment by yhl2018** [comment]
![1698757564389](https://github.com/MarSaKi/VLN-BEVBert/assets/36877347/be54cc57-95f0-4d72-800f-17cac16b56a2)
CLIP-ViT-B-16-views-habitat.hdf5 这个文件是哪个脚本生成的啊？没有找到对应的名字呢？

**Comment by yhl2018** [comment]
@MarSaKi 麻烦问您一下，训练ETPnav 的pretrain，和现在的这个BEVBert代码是完全一样的吗？以下几个特征也都是x需要的吗

**Comment by MarSaKi** [comment]
The pre-training code for BEVBert and ETPNav is not exactly the same. You can download the “CLIP-ViT-B-16-views-habitat.hdf5“ file from [here.](https://drive.google.com/file/d/1S8jD1Mln0mbTsB5I_i2jdQ8xBbnw-Dyr/view?usp=sharing)
